import type { Restaurant } from "./provider";

function mapsUrl(name: string, address: string): string {
  return `https://maps.google.com/?q=${encodeURIComponent(`${name}, ${address}`)}`;
}

function restaurant(input: Omit<Restaurant, "mapsUrl" | "openingHoursRaw">): Restaurant {
  return { ...input, mapsUrl: mapsUrl(input.name, input.address), openingHoursRaw: null };
}

/**
 * Fixed catalogue used whenever USE_MOCK_RESTAURANTS=true. Values are hand-set
 * rather than generated so scoring tests assert on stable numbers. The set is
 * deliberately spread across cuisines, price levels, ratings, distances,
 * dietary accommodation and open/closed status, and includes one three-location
 * chain so the "no three from one chain" rule has something to bite on.
 */
export const MOCK_RESTAURANTS: readonly Restaurant[] = [
  restaurant({
    id: "tacoria",
    name: "Tacoria",
    chainId: null,
    address: "123 College Ave",
    cuisine: "mexican",
    priceLevel: 1,
    rating: 4.6,
    distanceMiles: 0.8,
    accommodates: ["vegetarian", "vegan", "gluten_free"],
    openNow: true,
  }),
  restaurant({
    id: "seoul-bowl",
    name: "Seoul Bowl",
    chainId: null,
    address: "88 Telegraph Ave",
    cuisine: "korean",
    priceLevel: 2,
    rating: 4.4,
    distanceMiles: 1.4,
    accommodates: ["vegetarian"],
    openNow: true,
  }),
  restaurant({
    id: "noodle-house",
    name: "Noodle House",
    chainId: null,
    address: "441 Shattuck Ave",
    cuisine: "ramen",
    priceLevel: 2,
    rating: 4.1,
    distanceMiles: 1.1,
    accommodates: ["vegetarian"],
    openNow: true,
  }),
  restaurant({
    id: "green-fork",
    name: "Green Fork",
    chainId: null,
    address: "12 Center St",
    cuisine: "salad",
    priceLevel: 2,
    rating: 4.5,
    distanceMiles: 0.6,
    accommodates: ["vegetarian", "vegan", "gluten_free", "dairy_free"],
    openNow: true,
  }),
  restaurant({
    id: "bella-nonna",
    name: "Bella Nonna",
    chainId: null,
    address: "907 Grand Ave",
    cuisine: "italian",
    priceLevel: 3,
    rating: 4.7,
    distanceMiles: 2.3,
    accommodates: ["vegetarian"],
    openNow: true,
  }),
  restaurant({
    id: "pier-nine",
    name: "Pier 9 Oyster Bar",
    chainId: null,
    address: "9 Harbor Way",
    cuisine: "seafood",
    priceLevel: 3,
    rating: 4.5,
    distanceMiles: 2.9,
    accommodates: ["gluten_free"],
    openNow: true,
  }),
  restaurant({
    id: "smokestack-bbq",
    name: "Smokestack BBQ",
    chainId: null,
    address: "1400 Industrial Blvd",
    cuisine: "bbq",
    priceLevel: 2,
    rating: 4.3,
    distanceMiles: 3.4,
    accommodates: ["gluten_free"],
    openNow: true,
  }),
  restaurant({
    id: "dosa-corner",
    name: "Dosa Corner",
    chainId: null,
    address: "77 University Ave",
    cuisine: "indian",
    priceLevel: 1,
    rating: 4.6,
    distanceMiles: 1.9,
    accommodates: ["vegetarian", "vegan", "gluten_free"],
    openNow: true,
  }),
  restaurant({
    id: "athens-grill",
    name: "Athens Grill",
    chainId: null,
    address: "310 Solano Ave",
    cuisine: "greek",
    priceLevel: 2,
    rating: 4.2,
    distanceMiles: 1.6,
    accommodates: ["vegetarian", "halal"],
    openNow: true,
  }),
  restaurant({
    id: "pho-saigon",
    name: "Pho Saigon",
    chainId: null,
    address: "2020 San Pablo Ave",
    cuisine: "vietnamese",
    priceLevel: 1,
    rating: 4.4,
    distanceMiles: 2.1,
    accommodates: ["gluten_free"],
    openNow: true,
  }),
  restaurant({
    id: "slice-society-downtown",
    name: "Slice Society (Downtown)",
    chainId: "slice-society",
    address: "5 Main St",
    cuisine: "pizza",
    priceLevel: 1,
    rating: 4.0,
    distanceMiles: 0.4,
    accommodates: ["vegetarian"],
    openNow: true,
  }),
  restaurant({
    id: "slice-society-midtown",
    name: "Slice Society (Midtown)",
    chainId: "slice-society",
    address: "640 Midtown Blvd",
    cuisine: "pizza",
    priceLevel: 1,
    rating: 4.2,
    distanceMiles: 2.6,
    accommodates: ["vegetarian", "gluten_free"],
    openNow: true,
  }),
  restaurant({
    id: "slice-society-riverside",
    name: "Slice Society (Riverside)",
    chainId: "slice-society",
    address: "18 Riverside Dr",
    cuisine: "pizza",
    priceLevel: 1,
    rating: 3.9,
    distanceMiles: 3.8,
    accommodates: ["vegetarian"],
    openNow: true,
  }),
  restaurant({
    id: "burger-yard",
    name: "Burger Yard",
    chainId: null,
    address: "55 Fourth St",
    cuisine: "american",
    priceLevel: 2,
    rating: 4.1,
    distanceMiles: 1.2,
    accommodates: ["vegetarian"],
    openNow: true,
  }),
  restaurant({
    id: "sakura-omakase",
    name: "Sakura Omakase",
    chainId: null,
    address: "1 Pearl Ct",
    cuisine: "japanese",
    priceLevel: 4,
    rating: 4.8,
    distanceMiles: 4.2,
    accommodates: ["gluten_free"],
    openNow: true,
  }),
  restaurant({
    id: "cafe-lumiere",
    name: "Cafe Lumiere",
    chainId: null,
    address: "212 Ashby Ave",
    cuisine: "cafe",
    priceLevel: 2,
    rating: 4.3,
    distanceMiles: 0.9,
    accommodates: ["vegetarian", "vegan"],
    openNow: false,
  }),
  restaurant({
    id: "halal-cart-kitchen",
    name: "Halal Cart Kitchen",
    chainId: null,
    address: "899 Market St",
    cuisine: "middle_eastern",
    priceLevel: 1,
    rating: 4.5,
    distanceMiles: 1.7,
    accommodates: ["halal", "vegetarian"],
    openNow: true,
  }),
  restaurant({
    id: "casa-verde",
    name: "Casa Verde",
    chainId: null,
    address: "430 Mission Ave",
    cuisine: "mexican",
    priceLevel: 2,
    rating: 4.2,
    distanceMiles: 2.4,
    accommodates: ["vegetarian", "vegan"],
    openNow: true,
  }),
  restaurant({
    id: "golden-wok",
    name: "Golden Wok",
    chainId: null,
    address: "66 Webster St",
    cuisine: "chinese",
    priceLevel: 2,
    rating: 3.9,
    distanceMiles: 2.8,
    accommodates: ["vegetarian"],
    openNow: false,
  }),
  restaurant({
    id: "injera-house",
    name: "Injera House",
    chainId: null,
    address: "1501 Alcatraz Ave",
    cuisine: "ethiopian",
    priceLevel: 2,
    rating: 4.6,
    distanceMiles: 3.1,
    accommodates: ["vegetarian", "vegan", "gluten_free"],
    openNow: true,
  }),
];
